// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBHoB5Klb4BjRCCW2buFppXl7gAtxsybs',
    appId: '1:1019267715025:web:3b2759aa86edca817f5af0',
    messagingSenderId: '1019267715025',
    projectId: 'newsapp-d7366',
    authDomain: 'newsapp-d7366.firebaseapp.com',
    storageBucket: 'newsapp-d7366.firebasestorage.app',
    measurementId: 'G-KJM2375T1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChBfQ92XozW_AVBGx-mHMpZ1_ZA2ZjEDQ',
    appId: '1:1019267715025:android:65a7f07ea3ed1c977f5af0',
    messagingSenderId: '1019267715025',
    projectId: 'newsapp-d7366',
    storageBucket: 'newsapp-d7366.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWWKXm5nRHR2wJyELCl5itz5Kw_LHjgNU',
    appId: '1:1019267715025:ios:39428948ef4f1b6d7f5af0',
    messagingSenderId: '1019267715025',
    projectId: 'newsapp-d7366',
    storageBucket: 'newsapp-d7366.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );
}
